components/markdown/components/code-block.js
- Add syntax highlighting for `hljs` which is used to parse markdown code blocks.
=> add bash syntax highlighting

CONTRIBUTING.md
- Added a line in the contributing guidelines to make sure contributors run `yarn build` before submitting the PR because vercel will fail and give no indications as of why (just a 404 page) if there are errors in the build.
=> Update CONTRIBUTING.md to reflect the need of "yarn build"

docs/github/builder.md
- Clarify keystore name is required to generate keystore
- Point out custom keystore must not be checked in the Unity player settings
I ran into these two points when trying to build an android app with this action, otherwise the signing works fine :)
=> Clarify documentation about androidKeystoreName

docs/github/builder.md
The link used to point to https://github.com/features/actions.
This PR changes the link to https://github.com/marketplace/actions/unity-builder, so that it points to the actual page for the builder.
- Fixed a link that pointed to the wrong URL.
=> Fix Unity - Builder link in builder.md

docs/troubleshooting/common-issues.md
Add 2 possible solutions for this error when running Gradle while having emojis inside any environment variables.
```
Error: 3.690 [ERROR] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: started DaemonCommandExecution[command = Build{id=69dbd5b3-10f2-488e-8640-977da68733f9, currentDir=/github/workspace/Temp/gradleOut/launcher}, connection = DefaultDaemonConnection: socket connection from /127.0.0.1:33657 to /127.0.0.1:43866] after 0.0 minutes of idle
```
=> Add known issue with older Gradle versions

docs/gitlab/activation.md, docs/gitlab/android.md, docs/gitlab/getting-started.md
In the gitlab docs:
- Update links to docker images
- Update license variable name to `UNITY_LICENSE`
- Update note at the top of Android page about requiring a specific license variable
=> gitlab docs updates

components/layout/main/documentation-sidebar.js, docs/github/ios.md
I recently add CI/CD for one of my iOS projects, and It was a very time-consuming task!
Both because of the lack of a complete iOS CI/CD tutorial with unity and also the [apple recent changes](https://github.com/fastlane/fastlane/issues/18098?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE1NDQwMjAwMjU6NTE3MjI5Ng%3D%3D#issuecomment-774172059), which make old tutorials broken.
So I create this document,  I hope it's helpful
=> Add github/iOS documentation

docs/gitlab/02-activation.md
The UNITY_USERNAME variable misleadingly is not supposed to contain the users Unity Username.
It only works with the unity email address as already documented for local usage.
- Documented correct usage of UNITY_USERNAME variable in gitlab activation documentation
=> Unity Username should be filled with E-Mail

components/docs/versions/build-failure-details.tsx, components/docs/versions/builds.tsx, components/docs/versions/date-time.tsx, components/docs/versions/unity-version.tsx
- This makes the table that contains the builds for each target platform collapsible.
- More detailed information about the build / docker image publication appears (renders on-open)
- Fix last updated timestamp for all jobs
=> Add additional build info in table

components/auth/safe-auth-check.tsx, components/docs/versions/builds.tsx, components/docs/versions/docker-image-link-or-retry-button.tsx, components/docs/versions/docker-image-link.tsx
- Add a button that can only be seen by admins that are logged in. 
- Currently admins are configured in the settings of versioning-backend.
- calling the endpoint that will trigger the actual build.
=> Retry builds

components/docs/versions/docker-image-link-or-retry-button.tsx
- Fix a bug where hooks weren't always reached inside `<DockerImageLinkOrRetryButton />`
=> Fix a bug where hooks weren't always reached

components/markdown/components/blockquote.module.css, components/markdown/components/blockquote.tsx, components/markdown/markdown-to-page-mapping.js
- Fixes #68 (add blockquotes rendering from markdown documents)
=> Add blockquote mapping to markdown mapper

docs/github/v2/15-deployment/android.md, docs/github/v2/15-deployment/ios.md
- Use deploy instead of release and Also further refining the android keystore options
=> Use deploy instead of release

.babelrc, components/layout/docs/edit-on-github-link.tsx, components/layout/docs/menu-sidebar.js, components/layout/header/source-links.tsx, components/layout/main/breadcrumb.js, package.json, pages/example.js, yarn.lock
- Convert all icons to use `react-icons` instead of `@ant-design/icons`
- Remove ant icons library from package.json and babel.
This should simplify moving toward ant with less support.
=> Remove ant icons lib

components/layout/header/search-bar.tsx
- The url to Algolia was different on the server and the client. Causing both a rerender and an error in the console. 
- The component was switched out for a simple link to Algolia that won't randomly break.
=> Fix bug in Sponsored by button from Algolia

docs/github/v2/01-getting-started.md, docs/github/v2/03-test-runner.md, docs/github/v2/04-builder.md
Encourage running CI on every push and pull request, and keep the environment localized to where they are needed, to reduce risk of them being leaked to a bad action.
- Use `on: [push, pull_request]`
- Localize environment variables to where they are needed
=> Improve examples

docs/github/v2/15-deployment/ios.md
The existing instructions did not work for me. In particular the definition of GIT_TOKEN was incorrect. My change adds a link to the current Fastlane match documentation that spells out what GIT_TOKEN should be, and those instructions worked correctly for me. I also added an extra step that seems necessary (the Fastlane deployment failed without it) which is to create the App in the App Store Connect site ahead of time.
- ...
=> Fix instructions for GIT_TOKEN/App Store Connect

components/layout/header/nav-bar.tsx
Bug introduced in following pr/discussion:  https://github.com/game-ci/documentation/pull/151#discussion_r624682949
Before:
After:
This was caused by not specifying height and width. Usually, we're able to only specify `width` and height is calculated automatically, but maybe it's different with svgs.
=> Use width and height to fix huge scroll bug

components/markdown/components/code-block.js, docs/troubleshooting/common-issues.md
About to compare no `console` vs `plaintext` + 
```js
hljs.registerLanguage('plaintext', require('highlight.js/lib/languages/plaintext'));
```
=> Remove console from syntax highlighting

docs/gitlab/deployment/android.md
Added more details to the Google Play Store deployment documentation on how to install the fastlane gem using a Gemfile.
- Added documentation on adding a Gemfile
- Added documentation regarding the release status for internal tracks
=> Added instructions for adding a Gemfile for Google Play deployment.

docs/github/v2/03-test-runner.md
https://github.com/marketplace/actions/upload-artifact is a 404
https://github.com/marketplace/actions/upload-a-build-artifact is the marketplace link for upload-artifact
- ...
=> Resolving dead link

next.config.js
- Updated next.js `antStylesPattern` to exclude files with a *.js format.
*Error log*:
```
./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/var/www/html/node_modules/node-fetch/lib'
> Build error occurred
/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:1
TypeError: (0 , _styleChecker.canUseDocElement) is not a function
at Object.sVM9 (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:311597:40)
at __webpack_require__ (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:31:31)
at Object.CC+v (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:66495:38)
at __webpack_require__ (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:31:31)
at Object.bmkC …
```
=> Fix yarn build command by updating style pattern regex.

docs/github/v2/01-getting-started.md
- Update the GitHub Actions documentation examples to include unique cache keys. If the key is not unique for each build, the cache will only get updated for the first time the job is run. By generating a unique cache key, every time the job is run, a new cache entry will be created, and as per GitHub docs: "If there are no exact matches, the action searches for partial matches of the restore keys. When the action finds a partial match, the most recent cache is restored to the path directory."
I'm not supper happy with how the examples are slightly different for the simple and advanced example. But I feel the simple example is more correct, and the advanced example would get really complex if we did it in a similar way, as it would require using the `format` function (as nested variable …
=> Docs examples: Generate unique cache keys

docs/github/v2/01-getting-started.md
Hi!
The "simple" workflow example for the [GH getting started guide](https://game.ci/docs/github/getting-started) includes a git-lfs pull as part of checkout, but doesn't warn people that this will eat up their data pack bandwidth. 
This PR adds a short explanation of the problem, as well as an extra example workflow that includes git-lfs caching (with steps taken directly from the reference project workflow: https://github.com/webbertakken/unity-reference-project/blob/main/.github/workflows/main.yml).
I'm open to alternatives, but since Git LFS is such a common use case, it seems important to flag early on to new users that this is a real problem with an easy solution. 
Thanks! :)
=> Add LFS example to GitHub Getting Started guide

components/docs/versions/build-failure-details.tsx
- Fixes #211 
- Using the Article component for the `build-failure-details.tsx` to maintain a consistent style
While changing this, I got confused, cause `code-block.js` defines its children property as a string (`children: PropTypes.string.isRequired`) but on the clipboard copy it accesses it with`children[0]`. 
But without casting it to an array it will only copy the first letter to the clipboard. Might be worth creating a new issue for this and investigate if it's possible to change. 
Following warning will be thrown
> Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `CodeBlock`, expected `string`.
This warning is thrown on all pages that make use of the CodeBlock component. 
Screenshot for easy comparison of the visual changes:
=> Updated CodeBlock properties

docs/github/v2/15-deployment/ios.md
Looks like we're using `itc_team_id(ENV['APPLE_TEAM_ID'])` in `Appfile` so we don't have to specify the `APPLE_TEAM_NAME` env var which was previously passed to `itc_team_name` if I'm not mistaken.
I'm in the process of automating one of my iOS apps with fastlane and looks like we don't use `APPLE_TEAM_NAME` anywhere.
Less is more! :tada:
=> Remove APPLE_TEAM_NAME from iOS docs

components/layout/header/source-links.tsx, docs/docker/01-docker-images.md, docs/github/v1/01-getting-started.md, docs/gitlab/01-getting-started.md, docs/gitlab/02-activation.md, docs/gitlab/03-example-project.md, docs/gitlab/custom-build-options.md, docs/gitlab/deployment/android.md, docs/gitlab/tests.md, docs/troubleshooting/common-issues.md
* I moved `unity3d-gitlab-ci-example` project to [gitlab GameCI organization](https://gitlab.com/game-ci)
* https://gitlab.com/game-ci/unity3d-gitlab-ci-example
* I moved `unity3d` legacy docker images project to [gitlab GameCI organization](https://gitlab.com/game-ci)
* https://gitlab.com/game-ci/unity3d
* I archived `unity3d` legacy docker images project
* I updated `default` branch from `master` to `main` on `unity3d-gitlab-ci-example`.
=> Update documentation links to point to gitlab org and main

components/layout/header/source-links.tsx
gitlab link updated in a different pr. I just felt that the docker link pointing to docker hub instead of github was a bit weird.
=> Update links to github projects

docs/github/v2/15-deployment/ios.md
This revamps the GitHub Actions deployment guide for iOS to much more aggressively assume readers are not familiar with the intricacies of Fastlane, match, iOS codesigning, or any of their associated ecosystems. See #248. 
I'm extremely open to suggestion here, especially as I know this is much more verbose than a lot of the other getting started guides.
My assumption is, once this is in an acceptable place and has been merged, this will serve as a loose jumping-off point for revisiting the GH Android deploy docs in a similar fashion. They'll be much simpler, but some of the high-level conceptual explanations can be similar.
Thanks!
=> Refresh GH iOS deployment guide

docs/github/v2/15-deployment/ios.md
Since users of gameci may not be familiar with fastlane and fastfiles, we clarify that `gym` is equivalent to `build_app` in case they are using a preexisting fastfile.
- ...
=> Clarify in iOS deploy docs that gym is an alias to build_app

docs/github/v2/15-deployment/android.md
This revamps the Android GitHub Actions deployment docs to be more in-depth and to not assume familiarity with Fastlane or Play Store deployment, in line with the new iOS deployment docs.
=> Revamp Android deployment docs

docs/03-github/03-test-runner.mdx
- Added basic documentation for github-actions test runner from changes part of release [v2.0.1](https://github.com/game-ci/unity-test-runner/releases/tag/v2.0.1) and PR https://github.com/game-ci/unity-test-runner/pull/182
=> Added Code Coverage Documentation for GitHub Actions

docs/03-github/06-deployment/ios.mdx
This expands the iOS deployment guide to include instructions for setting up Fastlane Match to run entirely on CI. This means that the whole codesigning and building for iOS process can happen on Actions, without requiring you to use a physical Mac.
Curious to hear thoughts -- this does greatly complicate this guide, but I think there's value in having a single answer to the whole process. I experimented a bunch with how to abstract this more cleanly, but couldn't come up with a better answer than "here are two separate workflows to set up match on CI and then actually run match".
=> Add Actions-based Fastlane Match workflow to iOS deployment guide

docusaurus.config.js
`/docs/index` was returning a 404, so pointed it at `/docs/`
=> Fix 'welcome' footer link

docs/03-github/06-deployment/ios.mdx
As per @davidmfinol in Discord, this adds the `sync_certificates` fastlane lane to the iOS deployment guide, which was referenced in the example workflow but not actually included in the example Fastfile. 
It also makes sure we’re consistently calling `bundle exec fastlane ios [command]` instead of just `bundle exec fastlane [command]`. The latter will work consistently on a Fastlane project with just iOS, but in a project with both iOS and Android it may fail depending on which platform has been set to the default. There’s no real downside to us being more verbose + precise.
=> Add sync_certificates lane to iOS deployment Fastfile

docs/03-github/06-deployment/ios.mdx
We've had a few complaints that some of the GH env vars / repo secrets are inconsistently named in the iOS deploy docs. This fixes at least some of those issues.
=> Standardize App Store Connect secret key names in iOS deploy docs

docs/03-github/04-builder.mdx, docs/03-github/06-deployment/ios.mdx
- Building android bundle(.aab) instructions are missing under Builder documentation, and exists in deployment to play store. Linked the relevant part in the Builder documentation.
- `bundle install` step sends a platform error when the `Gemfile.lock` is generated on an OS that differentiates from the OS the job uses, added the necessary lines to fix this error.
- iOS deployment job, as far as I could tell, had no steps that added ssh authorization to the private repository containing the app store certificates. Added 2 lines that fixed this issue.
=> Documentation improvements for android build and app store deployment

docs/03-github/03-test-runner.mdx, docs/03-github/04-builder.mdx, versioned_docs/version-1/04-github/03-test-runner.mdx, versioned_docs/version-1/04-github/04-builder.mdx
- Adds an additional level in the table of contents for unity-builder and test runner
=> feat: display an additional level in toc of test runner and builder docs

docs/11-circleci/03-build.mdx
- Add new `build` parameter in the documentation ([#27](https://github.com/game-ci/unity-orb/pull/27)).
=> docs: include new `build` parameter

lefthook.yml, package.json, tsconfig.json, yarn.lock
- Closes https://github.com/game-ci/documentation/issues/324
- Move `--skipLibCheck` CLI flag to `tsconfig.json`
- Run `typecheck` script on pre-commit instead of `tsc` with custom compilerOption flags
=> chore: #324 Fix type check of staged files

docs/11-circleci/03-build.mdx, docs/11-circleci/04-test.mdx
Document the following additions to the Unity Orb:
- `return-license`: https://github.com/game-ci/unity-orb/pull/29
- `no_output_timeout`: https://github.com/game-ci/unity-orb/pull/32
- `custom_parameter`: https://github.com/game-ci/unity-orb/pull/36
- `build-method`: https://github.com/game-ci/unity-orb/pull/36
=> docs: add new Unity Orb parameters

docs/11-circleci/03-build.mdx
- Added documentation for fetching git submodules under unity-orb project 
[[relating unity-orb PR-41]](https://github.com/game-ci/unity-orb/pull/41)
=> Added documentation for fetching submodules

docs/11-circleci/03-build.mdx
- Fix CircleCI's build example for macOS
=> fix: macOS example in CCI's build job

docs/11-circleci/02-activation.mdx
- Related to #352. In order to disable line wrapping, add `-w 0` option to the base64 command in the CircleCI activation process
=> fix: add -w option to base64 command in circleci activation process

docs/03-github/04-builder.mdx, package.json
- Add docs for `androidExportType`, `androidSymbolType`, `cacheUnityInstallationOnMac`, and `unityHubVersionOnMac`
- Add deprecation warning for `androidAppBundle`
- Update node requirements to allow for >=16.x
This supports game-ci/unity-builder#505
=> Update docs to reflect changes in unity builder PR#505

docs/02-getting-started/index.mdx, docs/09-troubleshooting/common-issues.mdx
This is a proposal to alter the `getting started` section and `common issues` to reflect that you need to add the temporary files created by the runners to your `.gitignore` to prevent their branch from becoming dirty.
It would resolve issue  #365 
- I expanded the `.gitignore` section in `01-getting-started.mdx`
- I extended the `dirty branch` common issue text to refer back to the section mentioned above.
- [ x ] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
- [ x ] Readme (updated or not needed)
- [ x ] Tests (added, updated or not needed)
=> Add the need for custom .gitignore extensions to the Getting Started guide. (#365)

firebase.json
- Add a redirect from `/discord` to the discord invite. `/discord` is used as a shorthand of that very invite and was washed away when we moved from Vercel to Firebase.
See Firebase Hosting [priority order](https://firebase.google.com/docs/hosting/full-config#hosting_priority_order) to understand how the redirect resolves with regards to the rewrites.
=> Fix discord link

docs/03-github/03-test-runner.mdx
I spotted this while reading the docs, this is the only section from `unity-test-runner` that mentions `unity-builder`. I haven't tested this, but I think it might be a mistake. Could it be copy paste error?
=> Update unity-test-runner docs for License Server

docs/03-github/03-test-runner.mdx
- Adds documentation for package testing setup tasks, caveats, and configuration options which will be relevant once [the package testing PR](https://github.com/game-ci/unity-test-runner/pull/164) has been merged into the Unity test runner.
<strike>NOTE: I'm blocked from completing the two remaining checklist items by #397 . Since the contributing guidelines say I should ensure there are no build errors before submitting the PR, I'll leave it in draft status until I can figure out a solution or workaround to my issue.
That said, this PR has all of the changes I planned to make - I'm only leaving it a draft for now as a formality.</strike>
Issues have been resolved!
=> Package testing documentation

docs/08-docker/03-customize-docker-images.mdx
- adjust the "add blender to docker" example
Running this example prior to this pr would return a parse error "ARG names can not be blank" 
=> remove space in arg assignment (docker example)

docs/03-github/06-deployment/steam.mdx
- Remove reference to ssfn as they are no longer used
=> Remove reference to ssfn

docs/03-github/02-activation.mdx
- add "On the 'Activate your license' page" in 02-activation.mdx
https://github.com/game-ci/documentation/issues/408#issuecomment-1713127374
- [c] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
=> add "On the 'Activate your license' page" in 02-activation.mdx

docs/03-github/04-builder.mdx
- Added a clarifying single-sentence note. See discussion in https://github.com/game-ci/docker/issues/229
=> Add note regarding use of `env` and `customParameters`

docs/03-github/06-deployment/ios.mdx
- Type in the iOS deployment guide
=> fix: typo in iOS setup page

docs/05-gitlab/02-activation.mdx, docs/09-troubleshooting/common-issues.mdx
- Add warning to gitlab and troubleshooting as well concerning #408
=> Add warning to gitlab and troubleshooting for activation

docs/03-github/04-builder.mdx
Old version 1.2.0 throws the error `E: Unable to locate package google-cloud-sdk`, version 1.3.0 fixes this. Tested here: https://github.com/JohannesDeml/Unity-GameJam-Template/commit/60af3abdad4ede3bd38a3055535c8570b15e81a7
- Update `free-disk-space` from version 1.2 to 1.3 in full example to make it work again
=> Fix free-disk-space version in example

src/components/docs/versions/builds/build-failure-details.tsx, src/components/docs/versions/builds/build-row.tsx, src/components/docs/versions/builds/builds.module.scss, src/components/docs/versions/builds/builds.tsx, src/components/docs/versions/date-time.tsx, src/components/docs/versions/docker-image-link-or-retry-button.tsx, src/components/docs/versions/docker-image-link.tsx, src/components/docs/versions/image-versions.tsx, src/components/docs/versions/major-editor-version.tsx, src/components/docs/versions/unity-version.module.scss, src/components/docs/versions/unity-version.tsx, src/components/docs/versions/unity-versions.tsx, src/components/molecules/tooltip/tooltip.module.scss, src/components/molecules/tooltip/tooltip.tsx
Original author: https://github.com/EliasVal
See https://github.com/game-ci/documentation/pull/412
- Fix versions page
=> Fix Versions page closes #410, credits to EliasVal <3

docs/03-github/01-getting-started.mdx, docs/03-github/04-builder.mdx, docs/09-troubleshooting/common-issues.mdx
- Added parallel execution of tests and build example
- Improved no space left on device options
Todo:
=> Add parallel execution of tests and builds example + improved no space left on device

docs/12-self-hosting/01-overview.mdx, docs/12-self-hosting/03-host-creation/03-QEMU/02-linux-cloudimage.mdx
Draft
Fixes:  
> Docs markdown link couldn't be resolved: (./04-host-provisioning/03-cloud-init/01-about.mdx) in "/home/runner/work/documentation/documentation/docs/12-self-hosting/01-overview.mdx" for version current
- change header 1 of 01-overview.mdx back to 'Overview' from 'about self hosting'
- change an instance of 'Cloud-Init' to 'cloud-init'
- change a bad internal link with an outdated file ref
=> Fix broken link causing pipeline to fail

docs/03-github/04-builder.mdx
=> Add runAsHostUser docs

docs/03-github/01-getting-started.mdx, docs/03-github/03-test-runner.mdx
- Add `containerRegistryRepository`, `containerRegistryImageVersion`, `chownFilesTo`, and `runAsHostUser`
=> Add Builder v4 Parity Docs for Test Runner

docs/03-github/03-test-runner.mdx
- Add documentation relevant to the use of `scopedRegistryUrl` and `registryScopes`
- Add documentation for private scoped registries and using the `UPM_REGISTRY_TOKEN` environment variable
=> feat: scoped registries

docs/03-github/06-deployment/ios.mdx, versioned_docs/version-2/03-github/06-deployment/ios.mdx, versioned_docs/version-3/03-github/06-deployment/ios.mdx
While following the documentation I encountered an issue while building for iOS for App Store / Testflight distribution that necessitated a change to the permission of the file "usymtool".
Here's the log:
```
warning: Run script build phase 'Unity Process symbols' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Unity-iPhone' from project 'Unity-iPhone')
** ARCHIVE FAILED **
The following build commands failed:
PhaseScriptExecution Unity\ Process\ symbols /Users/runner/Library/Developer/Xcode/DerivedData/Unity-iPhone-fspqhayqvhrnvthcqgdyuzoxkiww/Build/Intermediates.noindex/Arch …
```
=> Fix iOS build App Store (permission issue)

docs/03-github/06-deployment/steam.mdx
This PR follows the proposed change on https://github.com/game-ci/steam-deploy and adds documentation on the new option.
=> Update steam deploy documentation to include InstallScript option

docs/03-github/03-test-runner.mdx
- Added more explicit documentation on support for and setting up a private scoped registry.
=> feat: add docs for private registry

example/BuildScript.cs
When versioning: None is set the version values should not be overwritten with "none", but kept as is, since that matches the documentation
- Set the buildVersion and and bundleVersionCode only if the value makes sense
=> Change buildscript to only write version if it should be set

docs/03-github/04-builder.mdx
Added instructions about setting preprocessor directives in Unity, as described in https://github.com/game-ci/documentation/issues/473
Tested locally:
=> Add instructions about setting preprocessor macros
