LICENSE

Add License 📜

---

.editorconfig
.eslintignore
.eslintrc.json
.prettierignore
.prettierrc.json
next.config.js
package.json
yarn.lock

[//]: # (Shortly describe your changes below)
[//]: # (Use words like `added`, `removed`, `fixed`, `updated`)
- Add code style rules
- Fixes and enforcement of these styles will be in a separate PR
[//]: # (Feel free to add your own items)
[//]: # (Also check items that are not applicable)

Add code styles

---

.eslintrc.json
components/layout/base-layout.tsx
components/layout/documentation-layout.tsx
core/property-types.js
next-env.d.ts
package.json
pages/docs/[page].tsx
pages/docs/index.js

[//]: # 'Shortly describe your changes below'
[//]: # 'Use words like `added`, `removed`, `fixed`, `updated`'
- Adds proptypes
- ESLint is now happy
[//]: # 'Feel free to add your own items'
[//]: # 'Also check items that are not applicable'

Add proptypes 👨‍🏫

---

docs/github/test-runner.md

[//]: # 'Shortly describe your changes below'
[//]: # 'Use words like `added`, `removed`, `fixed`, `updated`'
- Add host-network parameter to test docs
[//]: # 'Feel free to add your own items'
[//]: # 'Also check items that are not applicable'

Add host-network parameter to test docs

---

docs/github/builder.md

[//]: # 'Shortly describe your changes below'
[//]: # 'Use words like `added`, `removed`, `fixed`, `updated`'
- Update builder documentation
- Add support for android builds and android version code
- Add Android Build Settings
- Add defaults for `allowDirtyBuild`
[//]: # 'Feel free to add your own items'
[//]: # 'Also check items that are not applicable'

Add android docs

---

components/layout/components/nav-bar.js

[//]: # 'Shortly describe your changes below'
[//]: # 'Use words like `added`, `removed`, `fixed`, `updated`'
- Changes source URLs to not go to the action but the repository instead.
- Add Unity Actions overview repository
[//]: # 'Feel free to add your own items'
[//]: # 'Also check items that are not applicable'

Add overview repo to sources

---

.github/pull_request_template.md

🧹 simplify pr template

---

CONTRIBUTING.md
docs/github/builder.md
docs/github/getting-started.md
docs/github/test-runner.md

- https://www.infoq.com/news/2020/10/github-main-branch/

change master to main

---

components/layout/components/documentation-sidebar.js
docs/gitlab/android.md
docs/gitlab/example-project.md
docs/gitlab/ios.md
docs/gitlab/tests.md
docs/travis/getting-started.md

- Updated gitlab docs and added at least something for travis.

Update gitlab documentation and add travis docs

---

.github/workflows/cats.yml

- A sneaky cat has entered the repository

a cat for your proactive effort

---

components/layout/components/documentation-sidebar.js

- Add CI icon for missing travis logo icon

Add CI icon for missing travis logo icon

---

components/layout/components/documentation-sidebar.js
package.json
pages/_app.tsx
yarn.lock

- This will add the possibility to add custom icons.
- Custom icons will behave properly in ant design because of their class name.
- Revamp all icons in the docs menu.

Add custom icons

---

docs/github/builder.md
docs/github/test-runner.md

REF: webbertakken/unity-test-runner#79
- add description for customImage parameter (builder)
- add description for customImage parameter (test-runner)

Update github documentations

---

docs/troubleshooting/common-issues.md

We talked about this quite a few times on discord, so here it is.

Add known issue concerning unity manual activation

---

components/layout/main/documentation-sidebar.js
docs/github/android.md
docs/github/ios.md

- Fix some issues with Github/iOS page 
- Add a new tutorial for Android deployment
- Move Android/iOS to Github/Deployment submenu

Github Android deployment guide

---

docs/github/android.md
docs/github/ios.md

- Add instructions for adding libraries that need Podfile (e,g Firebase) in Github/iOS
- Fix some typos in Github/Android docs

Add instructions for adding podfile to iOS

---

components/layout/base-layout.tsx
components/layout/header/nav-bar.tsx
pages/discord.js

Disable search for redirect (quickfix for discord redirect)

---

docs/github/activation.md

- Update `uses: game-ci/unity-request-activation-file@v1.2` like in marketplace instead `webbertakken` action

Change uses to game-ci actual version

---

core/menu-structure.json

- Fix missing updated menu structure

Add missing menu structure

---

components/docs/versions/repo-versions.tsx
components/docs/versions/version.tsx
components/docs/versions/versions.tsx
components/layout/docs/menu-sidebar.js
components/layout/docs/menu/versioned-sub-menu.tsx
components/layout/docs/page.tsx
core/config.ts
package.json
pages/_app.tsx
pages/docs/docker/versions.tsx
styles/layout.css
yarn.lock

- Add statuses of Jobs in CI for docker images of all unity versions (MVP)
- Add menu button under /docs/docker/versions

Add version status page

---

components/docs/versions/unity-versions.tsx
tools/search/search-index.js

- This shows failures above other versions, so we can quickly identify whether the pipeline is currently stuck or not.

show failures at the top

---

components/docs/versions/builds.tsx
components/docs/versions/unity-version.module.css
components/docs/versions/unity-version.tsx
components/docs/versions/unity-versions.tsx
core/typings/declaration.d.ts

- Collapsable / Panel now works as carousel
- Table fits the content of an opened panel
- Typescript now recognizes `component-name.module.css`

Table style and ux cleanup

---

components/docs/versions/builds.module.css
components/docs/versions/builds.tsx
components/docs/versions/unity-version.module.css

- Set sticky for each level to explore builds more easily on the versions page

completely not overengineered idea that came from a dream

---

components/auth/safe-auth-check.tsx
components/docs/versions/build-failure-details.tsx
components/docs/versions/builds.tsx
components/docs/versions/docker-image-link-or-retry-button.tsx
components/docs/versions/show-and-copy-change-set-hash-button.tsx
components/docs/versions/unity-version.module.css
components/docs/versions/unity-version.tsx
components/markdown/components/code-block.js
components/reusable/spinner.module.css
components/reusable/spinner.tsx
core/config.ts
core/hooks/use-authenticated-endpoint.tsx
core/hooks/use-clipboard.tsx
core/hooks/use-https-callable.tsx
core/hooks/use-notification.tsx

- Allow admins to retry builds. 
- Instructions are given to first delete the build that is checked in the docker publication/retry workflow
- Admins get feedback through a notification about whether the retry was scheduled or not.
- A spinner will be shown once the workflow has reported in (see step in 3rd screenshot)

Retry builds

---

components/docs/versions/unity-version.tsx

- Map statuses to icons in the versions overview

Map CiJob statuses to icons

---

components/docs/versions/unity-version.tsx
components/reusable/spinner.tsx
components/reusable/spinner/three-dots.tsx

- Adds pending state in the versions page

Add pending state to versions page

---

docs/github/v2/15-deployment/android.md
docs/github/v2/15-deployment/ios.md

Update deployment docs

---

components/layout/header/source-links.tsx

Reorder source links

---

docs/github/v2/15-deployment/android.md
docs/github/v2/15-deployment/ios.md

Fix Gemfile

---

docs/github/v2/15-deployment/android.md
docs/github/v2/15-deployment/ios.md

- Add context and spacing to yml to make it easier to copy-paste

Add context and spacing to yml

---

docs/github/v2/04-builder.md

Typo: StaticBulidMethod -> StaticBuildMethod

---

core/menu-structure.json
package.json

- This will make regenerating the menu automatic, before committing.

Pre commit hook for menu

---

pages/docs/index.js

Add discord widget to docs home

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other.md
.github/pull_request_template.md

Update issue templates

---

docs/github/v2/02-activation.md

- Clarify difference between personal and professional licenses
- Use a single code snippet for the workflow, for easier copy-paste
- Clarify that the workflow should only be manually run once.

Improve activation docs

---

assets/styles/antd-custom.less

- Fix missing background color

Fix missing background color

---

components/pages/home/home-page.tsx
components/pages/home/section/code-examples-section.tsx
components/pages/home/section/gallery-section.tsx
components/pages/home/section/pricing-section.tsx
components/pages/home/section/section-module.scss
components/pages/home/section/who-is-using-game-ci-section.tsx

- Update the homepage with some quick renamings after talk with @GabLeRoux.

quick renamings after talk with gab

---

components/pages/docs/edit-on-github-link.module.scss
components/pages/docs/edit-on-github-link.tsx
components/pages/docs/sidebars/menu-structure-sidebar.js
core/menu-structure.json
docs/introduction/getting-started.md

- Add documentation for beginners in the "Getting started" section

Getting started docs

---

docs/github/v2/15-deployment/android.md

Android: Add details about app "draft" status

---

docs/github/v2/01-getting-started.md

- Fixes https://github.com/game-ci/documentation/issues/179

Improve semantics

---

docs/github/v2/15-deployment/ios.md

Fix broken links

---

docs/github/v2/15-deployment/ios.md

Minor improvement to leverage environment variables and provide smoother integration.

Inline app identifier

---

components/pages/docs/documentation-index.tsx
components/pages/home/header.tsx
components/pages/home/home-page.tsx

Add a favicon in the landing page 
Refactor headers

Add a favicon in the landing page + refactor headers

---

docs/github/v2/15-deployment/ios.md

Remove extraneous space character from ios.md

Remove extraneous space character from ios.md

---

docs/gitlab/01-getting-started.md

Updated the documentation to help in case the unity project is not at the root of the repository.
- ...

Update getting started to ease specifique case

---

components/markdown/components/embedded-link-or-paragraph.tsx
components/markdown/markdown-components.js
docs/gitlab/01-getting-started.md
yarn.lock

- Create EmbeddedLinkOrParagraph
- Support embedding youtube links

Support embedding youtube links

---

docs/gitlab/01-getting-started.md

- I've edited and re-uploaded the community video. And updated the youtube embed with the new url.

Updated community video for gitlab getting started.

---

.github/FUNDING.yml
README.md

- Indicate how to support us by adding the donation link in the readme and to the funding configuration

Indicate how to support us in the readme

---

docs/github/v2/04-builder.md

Mention the `Tag` versioning strategy

Document `Tag` versioning strategy

---

components/markdown/components/code-block.js
docs/github/v2/01-getting-started.md

- Added copy button to copy the code snippet to the clipboard.
- [ x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [ x] Readme (updated or not needed)
- [x ] Tests (added, updated or not needed)
Closes https://github.com/game-ci/documentation/issues/204#issuecomment-893231819

Add feature of copy button to copy to clipboard

---

docs/github/v2/06-remote-builder.md

Fix typos on remote builder page

---

docs/github/v2/15-deployment/ios.md

- Add comment about prerequisites for ios guide

Update ios docs messaging

---

docs/gitlab/custom-build-options.md

- The character used for indentation was wrong.
- Fixes #202

Fixed indentation

---

docs/github/v2/15-deployment/android.md

- Do not recommend online base64 encoder for secrets

Do not recommend online base64 encoder for secrets

---

docs/github/v2/15-deployment/ios.md

- Simplify the docs around match, certificates, and code signing for ios

Simplify the docs around match, certificates, and code signing for ios

---

docs/github/v2/15-deployment/steam.md

Add Steam page

---

docs/github/v2/03-test-runner.md

- Update documentation for input to unity-test-runner
- Moved `unityVersion` and `customImage` to the front of the documented options
- Moved `customParameters` up to better align with mental model
- Added `sshAgent` and `gitPrivateToken`
- See related PR: https://github.com/game-ci/unity-test-runner/pull/155

Sync documentation for unity-test-runner

---

docs/github/v2/04-builder.md

- Moved `targetPlatform` to the front of the list, as it is the only required input
- Moved `customImage` and `projectPath` to better match the order in test-runner
- Added details for `customParameters`, including explicitly describing both use cases, and link to Unity docs
- Added `sshAgent`, `gitPrivateToken`, and `chownFilesTo`

Sync builder docs

---

docs/github/v2/15-deployment/steam.md

As you recommend to use the semantic versioning in the documentation of the builder, it might be useful to show how to use this version in the steam-deploy example. Especially since the currently used method creates different version names.
Additionally I added the `needs` section to the deployment job as it shouldn't run in parallel with the build job.

Use version from build in steam-deploy example

---

docs/github/v2/03-test-runner.md

Adds a tiny bit of clarity to documentation regarding what testing customParameters are
Closes https://github.com/game-ci/unity-test-runner/issues/163
- [ x Tests (added, updated or not needed)

Specify customParameters is the Unity Test Framework customParameters

---

docusaurus.config.js
lefthook.yml
package.json
yarn.lock

- Fixes #271 
- Fixes ESLint taking forever as mentioned in https://github.com/game-ci/documentation/pull/259#issuecomment-1129554584

feat: link GTM and GA4

---

docusaurus.config.js

fix: broken edit links

---

.github/workflows/search-trigger.yml
algolia.config.js

feat: manual trigger for search crawler

---

.eslintignore
.eslintrc.json
.github/workflows/cats.yml
.github/workflows/checks.yml
.github/workflows/code-styles.yml
.prettierignore
codecov.yml
docs/03-github/06-deployment/ios.mdx
jest.config.js
lefthook.yml
package.json
src/components/auth/safe-auth-check.tsx
src/components/docs/versions/date-time.tsx
tests/__mocks__/fileMock.js
tests/test-utils.tsx
tests/tsconfig.json
yarn.lock

Updated the basic test suites to test separately and also in CI
Checks on pre-commit
- Code formatting (changed files)
- Code styles (changed files)
- Type checks (changed files)
- Tests related to changed funcationality
Checks in CI
- Code formatting (whole repo)
- Code styles (whole repo)
- Type checks (whole repo)
- Tests (all of them)

chore: enforce linting - add test setup

---

docs/03-github/05-returning-a-license.mdx
docs/03-github/06-deployment/android.mdx
docs/03-github/06-deployment/ios.mdx

- Use v2 for return-license
- Use `.` instead of `-` for numbering, to be consistent with the Steam page
- Correct the numbers so that they are sequential

Fix numbering

---

docs/03-github/06-deployment/ios.mdx

- Need to indicate ios in lane

Indicate ios in lane

---

docs/03-github/06-deployment/ios.mdx

- Add more integration for sync_certificates

Add more integration for sync_certificates

---

docs/05-gitlab/02-activation.mdx
docs/09-troubleshooting/common-issues.mdx
docs/10-faq/index.mdx
docusaurus.config.js
vercel.json

- Add FAQ page
- Add some links to FAQ
- Add a redirect so we can call `/faq`
Closes #300

Add FAQ page

---

docs/03-github/04-builder.mdx

- Clarifies how to increment major or minor version.
- Clarifies that the `v` prefix is optional.

Add clarifications about semantic versioning

---

.github/workflows/cats.yml

chore: update action-cats

---

docs/11-circleci/04-test.mdx

Replace wording in `Test` with what is used for the same sub-section in `Build`.

docs: fix inconsistency in the `Test` section

---

docusaurus.config.js

- This adds the merchandise (stickers, shirts) link to the top left nav and at the bottom under community.
- Also cleans up some other link texts and placements

feat: add merch link

---

docs/03-github/02-activation.mdx
docs/03-github/03-test-runner.mdx
docs/03-github/04-builder.mdx

- Added basic documentation on the license server option

Add basic documentation of the option unityLicensingServer

---

docs/03-github/03-test-runner.mdx

- Fix header level for coverageOptions

Fix header level for coverageOptions

---

docs/03-github/06-deployment/android.mdx

- Add androidTargetSdkVersion to docs

Add androidTargetSdkVersion to docs

---

docs/03-github/06-deployment/android.mdx

- Remove small typo in Android deployment

Remove small typo in Android deployment

---

docs/03-github/06-deployment/steam.mdx

- Update steam docs to mention TOTP

Update steam docs to mention TOTP

---

firebase.json

- Fixes https://github.com/game-ci/documentation/issues/379

fix invite

---

docs/10-faq/index.mdx

Document image build process in FAQ closes #387

---

docs/03-github/04-builder.mdx

- Updated GitHub builder documentation example for customParameters usage to reflect modern command for building a server.
Related PR: https://github.com/game-ci/unity-builder/pull/532
Discussion: https://github.com/game-ci/documentation/issues/240

Update custom parameter example for server builds

---

example/BuildScript.cs

- Update build script for standaloneBuildSubtarget

Update build script for standaloneBuildSubtarget

---

docs/03-github/04-builder.mdx

Fix for https://github.com/game-ci/unity-builder/issues/525

Fix github RSA key error

---

example/BuildScript.cs

Fix BuildScript.cs

---

docs/03-github/01-getting-started.mdx
docs/03-github/04-builder.mdx
docs/03-github/06-deployment/android.mdx
docs/05-gitlab/02-activation.mdx
docs/09-troubleshooting/common-issues.mdx

- Update from v2 to v3 for default GitHub actions
- Add free disk space action and fix #361

Add free disk space action and fix #361

---

docs/03-github/03-test-runner.mdx
docs/03-github/04-builder.mdx

complementary documentation for 
* https://github.com/game-ci/unity-builder/pull/568
* https://github.com/game-ci/unity-test-runner/pull/240

add documentation for working with multiple ssh keys

---

docs/03-github/06-deployment/android.mdx

- Replace androidAppBundle with androidExportType

Replace androidAppBundle with androidExportType

---

docs/03-github/04-builder.mdx

- Fix typo for containerRegistryImageVersion

Fix containerRegistryImageVersion typo

---

docs/03-github/02-activation.mdx

- Fix path to current location of secrets

Change update github path to action secrets

---

docs/03-github/03-test-runner.mdx

This is a followup change to #446. I simply reversed order of enumeration so it's easier to follow.

Small fix in viewing test results

---

docs/03-github/04-builder.mdx

- Added missing secrets to example workflow

Add missing secrets to example workflow

---

docs/03-github/04-builder.mdx
package.json
yarn.lock

- Added docs for skipActivation

Skip activation docs

---

docs/03-github/04-builder.mdx

- Added docs for `enableGpu` action
- Change introduced by [this PR](https://github.com/game-ci/unity-builder/pull/636)

enableGpu docs

---

docs/03-github/03-test-runner.mdx

Add missing email and password to code snippet. This has been [discussed on discord here](https://discord.com/channels/710946343828455455/1175793166645997698/1228749712795111446).

Update test runner example for proper personal license setup

---

docs/03-github/06-deployment/steam.mdx

- Set build step id to `buildStep` to help readers avoid confusion.

Update steam.mdx: Set build step id to `buildStep` to help readers avoid confusion.
